### ISSUE TITLE
Add documentation with clearer examples

### ISSUE THREAD

**Issue by brunopulis** [obetomuniz/tatooine#14]
Hi @obetomuniz, first congratulations on the project. I would like to suggest an improvement in the documentation of the examples.

Perhaps an HTML page or in the README with clearer examples will be better. I was a little confused about how to use Tatooine.

For example:
 
```js
Tatooine([rss]).then(...)
```

What do I need to do here?

**Comment by obetomuniz** [comment]
Glad that you tested the lib and for report this issue, @brunopulis. 

Are you suggesting to be more transparent on what is returned in the `.then` the statement, right? There are a few examples in the docs, and I have plans to add more recipes, but yeah, I fully agree with you about the data returned on `.then` not being as clear as it can be, I will improve the current docs/examples in this way. Thanks again for report this issue. 💯

**Comment by obetomuniz** [comment]
Closed by https://github.com/obetomuniz/tatooine/commit/bde4d0f676babdfb7b6bb1703c924c90f363eb9b
