### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by MarcoPolo** [obetomuniz/tatooine#71]
This project is great! Thanks a ton for doing this. It's well thought out and very flexible.

One thing I'd love to see is some TS definitions. I'm happy to add them following the schema engine docs, if you're open to it.

**Comment by obetomuniz** [comment]
Hey @MarcoPolo 👋  Thank you for the suggestion. I'm not prioritizing this, for now, so feel free to submit TS definitions here. For sure it will be much appreciated.

**Comment by obetomuniz** [comment]
Closed by https://github.com/obetomuniz/tatooine/commit/178b8ea5e640e64730cbbb8e8051cd7cd57c9f06
